//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_imaging.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalImageEntities : DbContext
    {
        public DigitalImageEntities()
            : base("name=DigitalImageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<docType> docTypes { get; set; }
        public virtual DbSet<fileInfo> fileInfoes { get; set; }
        public virtual DbSet<fileType> fileTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<uenType> uenTypes { get; set; }
        public virtual DbSet<user_auditTrail> user_auditTrail { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<view_fileInfo> view_fileInfo { get; set; }
    }
}
