//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_imaging.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_fileInfo
    {
        public int id { get; set; }
        public string fileUniqueID { get; set; }
        public string imageList { get; set; }
        public Nullable<System.DateTime> pro_date { get; set; }
        public string rumNum { get; set; }
        public string uenValue { get; set; }
        public Nullable<int> status { get; set; }
        public string maker { get; set; }
        public string chacker { get; set; }
        public string genPDF { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string fileName { get; set; }
        public string uenName { get; set; }
        public string docName { get; set; }
    }
}
